### PR TITLE
Encircle launch icon after finishing automatic update

### LINKED ISSUE #375: Add visual indicator for finished update on app launch
Once the automatic silent update on app launch has finished, the yac icon should change somehow to show this, e.g. by encircling the logo.

### PR DESCRIPTION
**Pull request by paetz**
Resolves #375

### CODE REVIEW

**Comment by chrgernoe** [comment]
Cool would be, if the circle is drawn clock wise while loading instad of just appearing.

**Review by chrgernoe — CHANGES_REQUESTED** [review]
You need to provide two versions, one for the main and the other for the dev release because you just override the the "Dev" below the icon. I just realized that this is already the case in the current release.

**Comment by paetz** [comment]
> Cool would be, if the circle is drawn clock wise while loading instead of just appearing.

yes, of course but this would be pretty difficult to implement.

**Comment by paetz** [comment]
> You need to provide two versions, one for the main and the other for the dev release because you just override the the "Dev" below the icon. I just realized that this is already the case in the current release.

? I don't understand. Dev- or stable version shouldn't matter. The launch screen icon is the same for both versions.

**Comment by chrgernoe** [comment]
> > Cool would be, if the circle is drawn clock wise while loading instead of just appearing.
> 
> yes indeed, but this would be pretty difficult to implement.

It is a nice gimmick. Since I have seen apps which have something similar, I guess there you probably find something in the internet.

**Comment by chrgernoe** [comment]
> > You need to provide two versions, one for the main and the other for the dev release because you just override the the "Dev" below the icon. I just realized that this is already the case in the current release.
> 
> ? I don't understand. Dev- or stable version shouldn't matter. The launch screen icon is the same for both versions.

Actual not because we also have different icons for both versions in the launcher. And as I wrote, in the dev version the icon has the word dev in it until you override it.

**Comment by paetz** [comment]
> > > Cool would be, if the circle is drawn clock wise while loading instead of just appearing.
> > 
> > 
> > yes indeed, but this would be pretty difficult to implement.
> 
> It is a nice gimmick. Since I have seen apps which have something similar, I guess there you probably find something in the internet.

If you'd like to have it, you may create a ticket. But keep in mind that
a) the update process at launch is pretty fast, so it might look odd
b) we do not send any status updates when updating countries & regions currently. If changing this, it would have an impact on the "update-all" feature in the region manager.

**Comment by paetz** [comment]
> > > You need to provide two versions, one for the main and the other for the dev release because you just override the the "Dev" below the icon. I just realized that this is already the case in the current release.
> > 
> > 
> > ? I don't understand. Dev- or stable version shouldn't matter. The launch screen icon is the same for both versions.
> 
> Actual not because we also have different icons for both versions in the launcher. And as I wrote, in the dev version the icon has the word dev in it until you override it.

Then we have different dev versions :) On my device (dev version 0.6) the icon on launching is the normal one without the "dev" lettering underneath.

**Review by chrgernoe — APPROVED** [review]

**Pull request merged**
