### PR TITLE
changed db interface from array to list

### PR DESCRIPTION
**Pull request by paetz**
This PR is a requirement for #131 .
Although List type may be slower due to dynamically allocated memory, I don't expect a huge impact on runtime since db interaction remains the bottleneck.

### CODE REVIEW

**Comment by chrgernoe** [comment]
Only to for me to understand. What is the reason form changing from array to list?

**Comment by paetz** [comment]
> Only to for me to understand. What is the reason form changing from array to list?

For speeding up tourbook import (and I believe the sector download as well), we need to reduce db requests.  The solution (addressed in #131) is to avoid updating the tables for every entry but rather create the complete lists dynamically and update the db only once at the end.

**Comment by Fabi2607** [comment]
I benchmarked the import. a simple db.beginTransaction / db.endTransaction massively reduces the overhead

**Comment by Fabi2607** [comment]
> I benchmarked the import. a simple db.beginTransaction / db.endTransaction massively reduces the overhead

To be clear for the import/download of Sectors/Summits/Routes from db-sandsteinklettern. I expect to tourbook to have the same issue

**Comment by Fabi2607** [comment]
The same performance benefit holds true for the tourbook.
 However, I still thing this change makes sense and reducing the DB requests is a good idea either way.

**Pull request merged**
